[[section-concepts]]
== Cross-cutting Concepts

****
En este apartado se describirá, generalmente las principales regulaciones e ideas de soluciones que serán relevantes en nuestro sistema.

.Modelo de dominio
TO DO // Diagrama conceptual con los temas relacionados con un problema específico

.Conceptos de experiencia de usuario (UX)
TO DO // explicacion interfaz de usuario que se añadirá cuando se decida.

.Conceptos de seguridad
La seguridad es uno de los temas claves en este proyecto. La aplicación al estar basada en SOLID archiva la información de cada usuario en su propio POD de forma descentralizada y segura, por lo que se evitan problemas de seguridad.

.Arquitectura y patrones de diseño
Se utilizará principalmente la arquitectura REACT para el diseño de la interfaz, la API de Google Maps para trabajar con las rutas y se trabajara con SOLID para almacenar la información personal de cada usuario en su propio POD.
Los patrones de diseño se añadirán más adelante.

."Under-the-hood"
TO DO // Se añadirá más adelante

.Conceptos de desarrollo
A lo largo del proyecto, el equipo tendrá que

* Plantear y desarrollar la idea sobre la que se trabajará después
* Implementar dicha idea.
* Testear y corregir los errores que se puedan producir.
