ignore:
  - "src/index.js"
  - "src/components/ReactComponents"
  - "src/components/components"
  - "src/components/AutoSaveSprinner/*"
  - "src/utils/index.js"
  - "src/layouts"
  - "src/serviceWorker.js"
  - "src/i18n.js"
  - "src/hooks/isLoading.js"
  - "src/constants/_navigation.lite.js"
  - "src/components/Notifications"
  - "src/components/Utils"
  - "src/containers/FormModel"
  - "src/containers/Friends"
  - "src/containers/Profile"
  - "src/containers/Mapa"
  - "src/containers/Register/register.container.js"
  - "src/containers/Register/register.component.js"
  - "src/containers/Register/RegistrationSuccess"
  - "src/containers/addRoute"
  - "src/containers/viewRoute"
  - "src/containers/RoutList/routList.container.js"
  - "src/containers/RoutesUser/routes.container.js"
